### PR TITLE
Add Replay Item types

### PR DESCRIPTION
**Pull request by lucas-zimerman**
## :scroll: Description
This PR adds the missing Event types for Replay to work with Hybrid SDK. (replay_event and replay_recording)

## :bulb: Motivation and Context
Replay is broken when sending using Android because the item header keeps getting replaced by "__unknown__"

## :green_heart: How did you test it?
following the contributing documentation of Capacitor.
deploying a local SDK and testing it with Sentry Capacitor, generating the following error/replay:
https://sentry.io/organizations/sentry-sdks/replays/sentry-capacitor:201ffafe1cc34c92bdf5ea467e6ab442/?referrer=%2Forganizations%2F%3AorgId%2Fdiscover%2F%3AeventSlug%2F&t=5&t_main=console

## :pencil: Checklist

- [X] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [X] No breaking changes

## :crystal_ball: Next steps

#skip-changelog (I don't think this is needed to be included on the changelog from the Android SDK since it has no impact for now on the Native SDK)

### CODE REVIEW

**Comment by markushi** [comment]
Nice one 👍 I think you need to run `./gradlew apiDump` on the project root folder to update the `.api` files, this should make the tests green.

**Review by adinauer — APPROVED** [review]
LGTM

**Comment by lucas-zimerman** [comment]
> Nice one 👍 I think you need to run `./gradlew apiDump` on the project root folder to update the `.api` files, this should make the tests green.

Oh I didn't know, will run it right now!

**Review by adinauer — APPROVED** [review]

**Review by bruno-garcia — APPROVED** [review]
Thanks Lukas

**Pull request merged**
