### PR TITLE
Add ``min.level`` configuration option and set events as breadcrumbs.

### PR DESCRIPTION
**Pull request by bretthoerner**
This does two things:

1. Adds a `min.level` configuration option that will drop events below the stated `Event.Level`. The default (`null`) does no filtering, just like today.
2. Adds every event, whether sent or not, to the breadcrumbs of the current context. This... seems useful to me, but could be considered a breaking change for some users, I guess?

I haven't run this or added tests. :smiley: Curious if it's a terrible idea first.

### CODE REVIEW

**Comment by dmclain** [comment]
I can see the appeal of this approach, for the "Just use the SentryAppender and set minLevel in your DSN" out of the box experience. It leaves a lot to be desired for a more advanced setup.

My goal state is "all logging at any level that makes it to a SentryAppender (or SentryBreadcrumbAppender) ends up on the threadlocal context and then when I do a Sentry.capture it gets sent to sentry". This PR would make that a little harder (but hey, I'll just land a SentryBreadcrumbAppender in my code and be done)

I think this is an instance where making the simple case easy/straightforward makes more complex configuration more challenging. It seems really straightforward to configure logging integrations through the logging system and to configure sentry settings via the sentry configuration methods, but I get excited enough about logging and exception reporting to go multiple rounds on something that combines both, so I'm a terrible data point.

**Comment by bretthoerner** [comment]
> My goal state is "all logging at any level that makes it to a SentryAppender (or SentryBreadcrumbAppender) ends up on the threadlocal context and then when I do a Sentry.capture it gets sent to sentry". This PR would make that a little harder

Wait, doesn't this do that?

`SentryAppender = DEBUG` = all logback logs bubble up to Sentry as an `Event`, get put into breadcrumbs, and then...
`min.level = ERROR` = Anything less than an `ERROR` gets dropped right before being sent to Sentry.

What's the difference from your desired outcome?

**Comment by dmclain** [comment]
When somebody does a `logger.error("the microservice pooped")` it would get sent as an event to Sentry and blow up our rate limits because of how often microservices poop, I want that as a breadcrumb and only send it up with an explicit Sentry.capture in our code.

**Comment by bretthoerner** [comment]
Would you use normal logging if we had an easier way to exclude exceptions by class? or package? That seems like the real root issue here to me.

**Comment by dmclain** [comment]
I think we would consider using the Spring SentryExceptionResolver, but we don't actually want to log a lot of the exceptions that that would pick up (like when our urls get fuzzed by a white hat security firm and we would get thousands of failed attempts to break the java integer parser). 

We also do custom sentry.capture in our quartz jobs with some handy breadcrumbs added. So I guess what I'm saying is I would never use the logging integration in our main app.

**Pull request closed without merging**
