### PR TITLE
Make SentryTransaction#finish thread-safe.

### LINKED ISSUE #1253: Transacrion/Span#finish should be thread-safe
The method `finish` should be thread-safe as it could be called from multiple threads.

cc @Tyrrrz @brustolin

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Make SentryTransaction#finish thread-safe.

## :bulb: Motivation and Context

Fixes #1253

## :pencil: Checklist

- [x] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
Is this @marandaneto what you meant?

**Comment by marandaneto** [comment]
> Is this @marandaneto what you meant?

I think that's a start, but not the whole thing, if the finish is called from multiple threads it'd be still racey, if we consider that a usage API error, that's ok, if we want to avoid these problems, then we'd need to do more.
let's see what @bruno-garcia says about https://github.com/getsentry/sentry-java/issues/1253#issuecomment-780406961
cus I am a bit lost

**Comment by bruno-garcia** [comment]
"make this thread-safe" gives me the impression we're designing the API to be called concurrently which doesn't make sense for `finish` which should be called once. It would then make more sense to flip the flag atomically so we don't capture the same transaction twice then. The name of this PR could then be:

`ref: use same throwable reference` to avoid confusion on what do we mean by it's making it thread-safe.
We're mutating the scope context without any further synchronization so by looking at this, finish is still "not thread-safe"

**Comment by marandaneto** [comment]
> "make this thread-safe" gives me the impression we're designing the API to be called concurrently which doesn't make sense for `finish` which should be called once. It would then make more sense to flip the flag atomically so we don't capture the same transaction twice then. The name of this PR could then be:
> 
> `ref: use same throwable reference` to avoid confusion on what do we mean by it's making it thread-safe.
> We're mutating the scope context without any further synchronization so by looking at this, finish is still "not thread-safe"

the naming `ref: use same throwable reference` would not be what I meant btw, this is the change that @maciejwalkowiak has changed to fix one of the racey possibilities, we didn't discuss only this field, but the whole method.

See this https://github.com/getsentry/sentry-java/issues/1253#issuecomment-780406961

eg call transaction.finish thread X (transaction is set on the scope, single hub is enabled)
thread Y and thread Z starts new child, finishes child, sets tags, sets throwable, mutate things
transaction.X finishes the execution of the finish method, but while so, the transaction/span state has been mutated by thread Y and Z, this is what we have discussed on the call.

**Comment by bruno-garcia** [comment]
> > "make this thread-safe" gives me the impression we're designing the API to be called concurrently which doesn't make sense for `finish` which should be called once. It would then make more sense to flip the flag atomically so we don't capture the same transaction twice then. The name of this PR could then be:
> > `ref: use same throwable reference` to avoid confusion on what do we mean by it's making it thread-safe.
> > We're mutating the scope context without any further synchronization so by looking at this, finish is still "not thread-safe"
> 
> the naming `ref: use same throwable reference` would not be what I meant btw, this is the change that @maciejwalkowiak has changed to fix one of the racey possibilities, we didn't discuss only this field, but the whole method.
> 
> See this [#1253 (comment)](https://github.com/getsentry/sentry-java/issues/1253#issuecomment-780406961)
> 
> eg call transaction.finish thread X (transaction is set on the scope, single hub is enabled)
> thread Y and thread Z starts new child, finishes child, sets tags, sets throwable, mutate things
> transaction.X finishes the execution of the finish method, but while so, the transaction/span state has been mutated by thread Y and Z, this is what we have discussed on the call.

TO make this thread-safe we'd need to synchronize access to all public methods here and make sure nothing gets mutated while we're running `finish`. This PR doesn't make "finish thread-safe".

**Comment by maciejwalkowiak** [comment]
Considering we are changing the `SentryTransaction` implementation anyway, I am closing this one.

**Pull request closed without merging**
