### PR TITLE
[SR] Fix various crashes

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

- Fix `IndexOutOfBoundsException` when tracking window changes. The problem here was that we had an `object RootViewSpy`, and it was shared between different instances of the ReplayIntegration, hence messing up things.
- Fix `IllegalStateException` when adding/removing draw listener for a dead view
- Fix `ConcurrentModificationException` when registering window listeners and stopping `WindowRecorder`/`GestureRecorder`
- Fix some TODOs in Windows.kt

## :bulb: Motivation and Context

Closes https://github.com/getsentry/sentry-java/issues/3859
Closes https://github.com/getsentry/sentry-react-native/issues/4234

## :green_heart: How did you test it?
Manually + automated

## :pencil: Checklist

- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Review by markushi — APPROVED** [review]
LGTM!

**Comment by iamrita** [comment]
Hi there! What version of sentry will this fix be incorporated in?

**Comment by iamrita** [comment]
Thanks for fixing this! What version of sentry should we update to on Android to incorporate this change?

**Comment by markushi** [comment]
@iamrita This fix will ship as part of the `7.19.0` release, which is about to ship in the upcoming hours.

**Comment by iamrita** [comment]
Great, looking forward to it!

**Comment by iamrita** [comment]
@markushi Any update on the `7.19.0` release?

**Comment by markushi** [comment]
@iamrita sorry for the delay, there was a small hiccup with our release pipeline, [but the release is out now](https://github.com/getsentry/sentry-java/releases/tag/7.19.0)!

**Pull request merged**
