### PR TITLE
Adds breadcrumb origin field

### PR DESCRIPTION
**Pull request by antonis**
## :scroll: Description

* [Adds a new `Breadcrumb` optional string property `origin`](https://github.com/getsentry/sentry-java/pull/3727/commits/71e9334af98251abcb807f61174cb5513c5abd69)
* [Updates the api dump (`./gradlew apiDump`)](https://github.com/getsentry/sentry-java/pull/3727/commits/787fd8d47a6e2fd90fd4e4aa3e67429b0dd89547)
* [Updates `Breadcrumb` unit tests](https://github.com/getsentry/sentry-java/pull/3727/commits/630eedd8a2819d976e59efd330882f547523759c)
* [Updates `Breadcrumb` serialisation tests](https://github.com/getsentry/sentry-java/pull/3727/commits/4cdfbbfe7cf3e9aacf66503d960fed5ea2ddd5c2). Note that [the dependency of the `SentryBaseEventSerializationTest`](https://github.com/getsentry/sentry-java/blob/main/sentry/src/test/java/io/sentry/protocol/SentryBaseEventSerializationTest.kt#L73) on [the `BreadcrumbSerializationTest.Fixture`](https://github.com/getsentry/sentry-java/blob/main/sentry/src/test/java/io/sentry/protocol/BreadcrumbSerializationTest.kt#L21) propagated the change in all the linked `json` test resources. A new `uuid` was generated for the `origin` test value following the existing pattern.

_Docs update PR: https://github.com/getsentry/sentry-docs/pull/11449_
_Related Cocoa PR: https://github.com/getsentry/sentry-cocoa/pull/4358_

## :bulb: Motivation and Context

Fixes https://github.com/getsentry/sentry-java/issues/3470
The discussion in https://github.com/getsentry/sentry-capacitor/pull/629#discussion_r1617321563 adds some context on the need of a new field to be used internally to solve a technical problem.

## :green_heart: How did you test it?
Unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by antonis** [comment]
Note:
I wan't able to successfully run the `Integration Tests / Ui tests` successfully after several attempts. I think this is not related with the changes on this PR but I'll be happy to investigate it more 🙇

**Comment by krystofwoldrich** [comment]
The UI tests are failing also in other PRs, definitely not related to the changes in this PR.
([fails in other PRs](https://github.com/getsentry/sentry-java/actions/runs/11067581047/job/30751234217?pr=3726#step:7:44))

**Review by krystofwoldrich — APPROVED** [review]
Thank you for adding the field. Looks good! 🚀

**Comment by markushi** [comment]
Re the failling test: Looks like an issue with the LeakCanary test, let me have a quick look!

**Comment by antonis** [comment]
All the tests are now 🟢 🎉 
Thank you for helping out @markushi 🙇

**Review by markushi — APPROVED** [review]
LGTM!

**Pull request merged**
