### PR TITLE
Fix: Sending errors in Spring WebFlux integration.

### LINKED ISSUE #1790: Spring Boot (Webflux): many unrelated http breadcrumbs are recorded with events
_Platform:_
- [x]  Spring Boot (Webflux server & WebClient) -> 2.5.5

_IDE:_
- [x]  IntelliJ -> 2021.2

_Build system:_
- [x]  Maven -> 3.6.3-jdk-11

_Platform installed with:_
- [x] Maven Central

The version of the SDK:
5.2.4

---
**I have the following issue:**

Many (tens or even ~hundred) unrelated http breadcrumbs recorded with events. These breadcrumbs are:
- Incoming server http requests (to actuator endpoints, for example)
- Outgoing http client requests to external services, but they are old and/or unrelated to original incoming server request

**Steps to reproduce:**
- Use spring-boot webflux server application
- Use sentry-spring-boot-starter
- Use actual sentry server (probably won't work with NoOpHub)
- Start app locally
- Put some load on application
  - I used 50 threads in jmeter accessing actuator health, info and prometheus endpoints without delays
  - prometheus worked better
- Make some meaningful requests which should cause some kind of error which should be sent to sentry
- Observe events on sentry server or via debugging SentryClient (less effective)

**Actual result:**
Screenshot from actual server-running instance
sentry webflux bug

**Expected result:**
Only a couple of related http breadcrumbs are present

**Personal thoughts**
Both SentryWebFilter & SentrySpanClientWebRequestFilter use HubAdapter, which uses static Sentry.getCurrentHub() method, which returns ThreadLocal instance of Hub.

It seems like this mechanism may not work correctly with reactive application, which serves requests on a small number of threads, and they are switched frequently.

As far as I know, there is a way of storing arbitrary request-related data in webflux:
- org.springframework.web.server.ServerWebExchange.getAttributes()
- org.springframework.web.reactive.function.client.ClientRequest.attributes()

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Fix sending errors in Spring WebFlux integration.

This time, without trying to find a workaround but rather using recommended reactive/reactor way of doing things: instead of copying hub every time executing thread changes, hub is set on Reactor context, which means:

Pros:
- we don't affect the performance as much as we did before - as copying hub happens only once per request
- there is no way that threads interfere with each other

Cons:
- when Sentry static methods are used, scope **is not attached to events**
- Logging frameworks also have no access to Sentry scope

## :bulb: Motivation and Context

Fixes #1790

## :green_heart: How did you test it?

Integration tests, sample project running on the side.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

Only classes marked as experimental are changed.

### CODE REVIEW

**Comment by bruno-garcia** [comment]
> Cons
> * when Sentry static methods are used, scope is not attached to events
> * Logging frameworks also have no access to Sentry scope

These are pretty big cons. Wouldn't this break the relationship of breadcrumbs and events from web-requests?
Also, this would break then any static use of `Sentry.captureException` in terms of having any web-request related information?

Not to say that it's not a better/right thing to do, but it brings to question if it's worth building this integration altogether since it's still fairly broken (though possible less broken if now we have info from the wrong request appended)

**Comment by maciejwalkowiak** [comment]
> Wouldn't this break the relationship of breadcrumbs and events from web-requests?
No, as long as breadcrumbs or events are added through a hub retrieved from Reactor context. So our out-of-the-box integration for error handling works as expected.

> Also, this would break then any static use of Sentry.captureException in terms of having any web-request related information?

Yes, I agree this is sub-optimal. I'll see if there is a way to make it work.

**Comment by maciejwalkowiak** [comment]
As far as I can tell - there is no way to do it without a considerable performance hit. Sleuth integration with Reactor, initially worked in a way that scope was copied between threads, now starting from version 3.0 they recommend "manual" mode: https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/integrations.html#sleuth-reactor-integration

There are *some* other solutions to this problem - mainly circulating around Reactor + MDC - but all are home-grown and each faces issues. 

I think having out-of-the-box solution for capturing unhandled exceptions in Webflux is useful for users, but at this stage we should not ship integration with static methods or logging statements, as every implementation seems to be risky to me.

**Comment by maciejwalkowiak** [comment]
Following [Reactor docs](https://projectreactor.io/docs/core/release/reference/#faq.mdc), the one other way to make it work, including static api and logback as a result is to add following method that will set the thread local and reset it after operator finished work:

```java
public static <T> Consumer<Signal<T>> withSentry(Consumer<T> logStatement) {
  return signal -> {
    if (!signal.isOnNext()) return;
      IHub currentHub = Sentry.getCurrentHub();
      IHub iHub = signal.getContextView().getOrDefault(SentryWebFilter.HUB_REACTOR_CONTEXT_ATTRIBUTE, null);
      if (iHub != null) {
        Sentry.setCurrentHub(iHub);
        logStatement.accept(signal.get());
        Sentry.setCurrentHub(currentHub);
      } else {
        logStatement.accept(signal.get());
      }
  };
}
```

Then, every call to static method on `Sentry` class, or logger, must be wrapped into `withSentry`.

```java
Mono<Person> create(Person person) {
  return Mono.delay(Duration.ofMillis(100))
      .publishOn(Schedulers.boundedElastic())
      .doOnEach(withSentry(s -> Sentry.captureMessage("Creating person")))
      .doOnEach(withSentry(__ -> LOG.error("ERROR LOG")))
      .map(__ -> person);
}
```

We can either add it to the code base, or add to docs. I would still keep it experimental. 

This marks the end of my investigation :-)

**Comment by bruno-garcia** [comment]
> Following [Reactor docs](https://projectreactor.io/docs/core/release/reference/#faq.mdc), the one other way to make it work, including static api and logback as a result is to add following method that will set the thread local and reset it after operator finished work:
> 
> ```java
> public static <T> Consumer<Signal<T>> withSentry(Consumer<T> logStatement) {
>   return signal -> {
>     if (!signal.isOnNext()) return;
>       IHub currentHub = Sentry.getCurrentHub();
>       IHub iHub = signal.getContextView().getOrDefault(SentryWebFilter.HUB_REACTOR_CONTEXT_ATTRIBUTE, null);
>       if (iHub != null) {
>         Sentry.setCurrentHub(iHub);
>         logStatement.accept(signal.get());
>         Sentry.setCurrentHub(currentHub);
>       } else {
>         logStatement.accept(signal.get());
>       }
>   };
> }
> ```
> 
> Then, every call to static method on `Sentry` class, or logger, must be wrapped into `withSentry`.
> 
> ```java
> Mono<Person> create(Person person) {
>   return Mono.delay(Duration.ofMillis(100))
>       .publishOn(Schedulers.boundedElastic())
>       .doOnEach(withSentry(s -> Sentry.captureMessage("Creating person")))
>       .doOnEach(withSentry(__ -> LOG.error("ERROR LOG")))
>       .map(__ -> person);
> }
> ```
> 
> We can either add it to the code base, or add to docs. I would still keep it experimental.
> 
> This marks the end of my investigation :-)

It sounds like this API is the way to go. We can document things to lead users the right path

**Comment by bruno-garcia** [comment]
Just noticed the snippet u shared is missing a try/finally to undo the hub thing in the finally block if the callback throws

**Comment by oliverorav** [comment]
Is there any update on this PR and generally about Sentry and WebFlux integration? As from @adinauer comment this is also a blocker to move forward with #1807 .

**Comment by adinauer** [comment]
@oliverorav I played around with this for a bit during our Hackweek and created this draft PR: https://github.com/getsentry/sentry-java/pull/2224

But as you can see it leads to quite a mess in the `PersonController` and I never finished working on it. It's also net been tested in any real application.

A way to improve on it I can think of is to somehow apply the mess using some sort of bytecode manipulation and make the right hub available without requiring the user to write the mess. This is just an idea though and not very high on our list of priorities at the moment unfortunately.

**Pull request closed without merging**
