### PR TITLE
Allow sentry to be included in library projects

### PR DESCRIPTION
**Pull request by linakis**

### CODE REVIEW

**Comment by bretthoerner** [comment]
Can you explain what exactly this does/allows?

**Comment by linakis** [comment]
It prevents throwing the `IllegalStateException` when someone includes the dependency inside a library project (that uses `apply plugin: 'com.android.library'` in gradle) instead of an app project (that uses `apply plugin: 'com.android.application'` in gradle). There is not reason why this check should fail for library projects.

**Comment by bretthoerner** [comment]
I'm trying to understand what it would mean for the Sentry Gradle plugin to be in a library.

The end-user application has to configure the `sentry-cli` to upload ProGuard files to Sentry -- so what is the benefit/purpose/reason for a library to include our Gradle plugin?

**Comment by linakis** [comment]
It's not necessarily a library that would be exposed to the public... i.e. in my use case i have multiple library modules that I re-use in various products. One of them is the `logger` module that I would like to encapsulate the sentry library to it... at the moment because of this restriction of the gradle plugin I have to add it in my app module and use it in my library project. I don't see a reason why you would intentionally want to exclude library projects from it.

**Comment by bretthoerner** [comment]
> I don't see a reason why you would intentionally want to exclude library projects from it.

Me neither, but I need to understand the purpose of the code I merge. :) Thanks for the details.

**Comment by linakis** [comment]
lol... yeah it was a matter of speech thing not an actual (personal) inquiry 😄

**Pull request merged**
