### PR TITLE
Upgrade Spring Boot to 2.3.4.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Upgrade Spring Boot to 2.3.4.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Review by marandaneto — APPROVED** [review]
LGTM

**Comment by bruno-garcia** [comment]
Just a reminder to generally target the lowest possible version here.
Not to force consumers of our lib to update their apps.

**Comment by bruno-garcia** [comment]
This is the latest version: https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter

Do we want to go this direction?

What woud be the lowest version we can target our lib that it would still compile/work?

**Comment by bruno-garcia** [comment]
We possibly need two versions here: One of the sample which can be this one (latest)
One for the lib which should be the lowest

**Comment by maciejwalkowiak** [comment]
I am not sure how does it work, but when projects use `spring-boot-starter-parent` (default for Spring Boot), versions from our starter get overwritten by the ones specified in Spring Boot. So we are not forcing to use the latest version.

But, to make sure that it does work with the range of versions it would be nice if we could test against all of them. Not sure how to do it though.

**Comment by bruno-garcia** [comment]
I find that an odd dependency resolution strategy. How do they make sure things are compatible?
If that's true we can be using an API that's not available on their older version there.

In general libraries target the lowest version they need. The app has that as a base requirement for compatibility with the framework.

**Pull request merged**
