### PR TITLE
Add Github action that checks formatting.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Adds Github action to check if code is properly formatted.

## :bulb: Motivation and Context

We often get PRs merged that do not have code properly formatted. As the result, formatting fixes sneak in to other PRs adding noise.

This change will prevent PR build success in case code is not properly formatted.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — COMMENTED** [review]
Does it push the diff back into the PR?

What about something like this: https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/format-code.yml

**Comment by marandaneto** [comment]
> Does it push the diff back into the PR?
> 
> What about something like this: https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/format-code.yml

I'd say it doesn't, and now I wonder what's the difference between this PR and this:

https://github.com/getsentry/sentry-java/blob/main/build.gradle.kts#L129-L131

because they do pretty much the same thing and the CI already calls `gradle build`

**Comment by maciejwalkowiak** [comment]
> > Does it push the diff back into the PR?
> > What about something like this: https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/format-code.yml
> 
> I'd say it doesn't, and now I wonder what's the difference between this PR and this:

It doesn't but I can add this action that commit changes back.

> 
> https://github.com/getsentry/sentry-java/blob/main/build.gradle.kts#L129-L131
> 
> because they do pretty much the same thing and the CI already calls `gradle build`

The difference is that calling `gradle build` only applies formatting configuration and with this PR the build will fail if code is not formatted.

**Comment by marandaneto** [comment]
> > > Does it push the diff back into the PR?
> > > What about something like this: https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/format-code.yml
> > 
> > 
> > I'd say it doesn't, and now I wonder what's the difference between this PR and this:
> 
> It doesn't but I can add this action that commit changes back.
> 
> > https://github.com/getsentry/sentry-java/blob/main/build.gradle.kts#L129-L131
> > because they do pretty much the same thing and the CI already calls `gradle build`
> 
> The difference is that calling `gradle build` only applies formatting configuration and with this PR the build will fail if code is not formatted.

I see, makes sense, I have this as a pre-commit hook actually.
https://github.com/getsentry/sentry-java/blob/main/hooks/pre-commit

but yeah CI would be great as well

**Review by marandaneto — APPROVED** [review]

**Pull request merged**
