### PR TITLE
Use latest log4j2 version

### PR DESCRIPTION
**Pull request by Falmarri**

### CODE REVIEW

**Comment by bretthoerner** [comment]
Thanks. Out of curiosity was this just to keep up to date or was `sentry-java` not working with your project before?

It looks like Travis is failing, if you rebase/merge master it should hopefully fix.

**Comment by Falmarri** [comment]
@bretthoerner Mainly the former. I use MapMessage extensively internally, and the 2.8 -> 2.9 binary incompatible change was specific to MapMessage. So the evictions are just slightly disconcerting to me.

**Comment by Falmarri** [comment]
Maybe instead of upgrading just mark it as `provided`? That should alleviate my eviction warning concern

**Comment by bretthoerner** [comment]
Good call.

**Pull request closed without merging**
