### PR TITLE
Missing unit fields for Android measurements

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Added missing unit field.
Added support for unknown fields in case new types come from Hybrid SDKs.

## :bulb: Motivation and Context
Fix https://github.com/getsentry/sentry-java/issues/2150
Part of https://github.com/getsentry/team-mobile/issues/31

## :pencil: Checklist

- [X] I reviewed the submitted code
- [X] I added tests to verify the changes
- [ ] I updated the docs if needed
- [X] No breaking changes

### CODE REVIEW

**Review by adinauer — APPROVED** [review]
LGTM

**Comment by marandaneto** [comment]
[This](https://github.com/getsentry/sentry-java/blob/eba572ac900ca2c58111c6b0db9730a64ac58533/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java#L269-L273) has to change, making a draft for now.

**Comment by philipphofmann** [comment]
@marandaneto, this PR has been lying around for a while. What can we do to move it forward?

**Comment by adinauer** [comment]
@marandaneto 

> [This](https://github.com/getsentry/sentry-java/blob/eba572ac900ca2c58111c6b0db9730a64ac58533/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java#L269-L273) has to change, making a draft for now.

Should be fixed now. Do you want to give my changes a review or can I merge this? Would need it for measurements.

**Comment by marandaneto** [comment]
> @marandaneto
> 
> > [This](https://github.com/getsentry/sentry-java/blob/eba572ac900ca2c58111c6b0db9730a64ac58533/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java#L269-L273) has to change, making a draft for now.
> 
> Should be fixed now. Do you want to give my changes a review or can I merge this? Would need it for measurements.

All good from my side, I can't approve my own PR, feel free to fix the conflicts and merge it, thanks for fixing this.

**Pull request merged**
