### PR TITLE
Extend CheckInUtils with check-in for a specific environment

### PR DESCRIPTION
**Pull request by maxhov**
## :scroll: Description
Extend `CheckInUtils` with an option to check in to a specific environment, which is currently not possible with `CheckInUtils`.

## :bulb: Motivation and Context
Currently it is not possible to check in to a specific environment with `CheckInUtils`. When monitoring a scheduled job that runs for multiple environments, it is helpful to be able to check in specific environments. To accomplish this in the current version requires copy, pasting and modifying the existing code to a custom class and adding it yourself.

## :green_heart: How did you test it?
Added a unit test

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed. https://github.com/getsentry/sentry-docs/pull/11826
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by adinauer** [comment]
Thanks for the PR, I'll retarget it to the v8 release.

**Comment by adinauer** [comment]
Oh boy, gimme a minute to resolve these conflicts.

**Review by adinauer — APPROVED** [review]
LGTM, @maxhov can you please take another look to make sure I didn't mess anything up while resolving conflicts?

**Comment by maxhov** [comment]
> LGTM, @maxhov can you please take another look to make sure I didn't mess anything up while resolving conflicts?

LGTM :)

**Comment by adinauer** [comment]
The changes in this PR were just released as part of [8.0.0-beta.3](https://github.com/getsentry/sentry-java/releases/tag/8.0.0-beta.3).

**Pull request merged**
