### PR TITLE
Optimize DateUtils performance.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Improves `DateUtils` performance. See benchmark results here: https://github.com/maciej-scratches/simple-date-format-benchmark.

While this improves the current state, we can consider also opting-out from using SDF completely and rely on `Calendar` class instead similar to: https://askldjd.wordpress.com/2013/03/04/simpledateformat-is-slow/

## :bulb: Motivation and Context

I noticed getting current timestamp in UTC takes significant amount of CPU time while running benchmarks for the performance feature. 

This class has been also pointed in https://github.com/getsentry/sentry-java/issues/1081

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
I'd love to use the new Java Date API from Java 8, but this would break a lot of Android devices :(

**Comment by maciejwalkowiak** [comment]
Are we taking thi decision anytime soon? If not, i believe we should optimize this class either with ThreadLocal or Calendar class.

**Comment by marandaneto** [comment]
> Are we taking thi decision anytime soon? If not, i believe we should optimize this class either with ThreadLocal or Calendar class.

nop, we can't break older OS versions, If the `ThreadLocal` version already speeds up, let's go for it.
Calendar is also broken if using UTC, it'll need workarounds too so not sure if it's gonna help anyway, let's go for ThreadLocal

**Review by marandaneto — APPROVED** [review]
LGTM

**Comment by bruno-garcia** [comment]
could we introduce an abstraction and inject a different one for Android?
So we can have the non shitty version for Java then?

**Comment by marandaneto** [comment]
> could we introduce an abstraction and inject a different one for Android?
> So we can have the non shitty version for Java then?

that sounds reasonable.

**Pull request merged**
