### PR TITLE
Enha: Add API validator and remove deprecated methods

### PR DESCRIPTION
**Pull request by marandaneto**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring

## :scroll: Description
Enha: Add API vlaidator and remove deprecated methods

## :bulb: Motivation and Context
We'd like to know when our API is broken, it's not back compatible.
`./gradlew apiCheck` is part of `./gradlew build` which is running on CI, so we don't need to do anything.
`./gradlew apiDump` is gonna be needed if API has changed and we are fine with it, changes will need to be committed.

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [X] All tests passing
- [ ] No breaking changes

It's breaking changes, but it's @Deprecated since 2.0 and we are going to a Major bump (4.0)

### CODE REVIEW

**Review by philipphofmann — APPROVED** [review]
LGTM.  

This info might be useful in the Contributing.md

> We'd like to know when our API is broke, it's not back compatible.
> ./gradlew apiCheck is part of ./gradlew build which is running on CI, so we don't need to do anything.
> ./gradlew apiDump is gonna be needed if API has changed and we are fine with it, changes will need to be committed.

**Comment by marandaneto** [comment]
> LGTM.
> 
> This info might be useful in the Contributing.md
> 
> > We'd like to know when our API is broke, it's not back compatible.
> > ./gradlew apiCheck is part of ./gradlew build which is running on CI, so we don't need to do anything.
> > ./gradlew apiDump is gonna be needed if API has changed and we are fine with it, changes will need to be committed.

the error message on `./gradlew build` if pretty clear about the `apiDump` if the API has changed, pretty much the same with `spotlessCheck` if your code is not formatted, so we are fine :)

**Review by maciejwalkowiak — APPROVED** [review]
This is awesome! I did not know such thing exists.

**Comment by marandaneto** [comment]
> This is awesome! I did not know such thing exists.

yeah I had this on my TODO for a long time, and then the 2nd lockdown came, I played a bit with platform improvements on the Dart repo too :D
The nicest thing is, it works on Java code as well, I'd hate if it was Kotlin only.

**Pull request merged**
