### PR TITLE
[QA] Offload System.loadLibrary call to background thread

### PR DESCRIPTION
**Pull request by markushi**
## :scroll: Description
Perform `System.loadLibrary()`  on a background thread.

## :bulb: Motivation and Context

Calling `System.loadLibrary()` causes StrictMode violations, as it performs disk reads, but any JNI calls like `initSentryNative` needs the libraries to be loaded beforehand.

Initializing the whole NDK off the main thread would be an option, but it has two main disadvantages:
* there's no guarantee that the NDK is initialized after `SentryAndroid.init()`, thus we could miss early startup crashes
* all NDK communication (setUser, setTag) needs to be done on a background thread as well

So the trick is to perform `System.loadLibrary()` as early as possible on a background thread, but still perform NDK init synchronous on the main thread. In my testing this works well, as the SDK init in-between takes longer than the `.loadLibrary()` calls, making the `loadLibraryLatch.await(2000, TimeUnit.MILLISECONDS)` return immediatelly.

## :green_heart: How did you test it?
Just manually, haven't found a better way yet.

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by markushi** [comment]
Comparing the performance metrics with other PRs, we can see a nice 35-45% improvement of the startup time 🚀

**Comment by kahest** [comment]
@markushi sounds very promising 👍 any creative ways to test this end-to-end?

**Comment by kahest** [comment]
for reference: this is related to/fixes (partially) https://github.com/getsentry/sentry-java/issues/3585 and https://github.com/getsentry/sentry-java/issues/3654

**Review by stefanosiano — APPROVED** [review]
Looks good!
Not sure how/if we can test it, but "logically" it works

**Review by romtsn — APPROVED** [review]
I think we wanted to make it part of the next major (8.x.x) - do we still wanna do that?

Aside, this looks good, and I think eventually we could offload the native init to the background thread as well, because we wanted to move `setTag`, `setBreadcrumbs` to background anyway.

**Pull request merged**
