### PR TITLE
chore(internal): Refactor view hierarchy to be more hybrid SDK friendly

### PR DESCRIPTION
**Pull request by krystofwoldrich**
## :scroll: Description
Refactor the view hierarchy processor for hybrid SDKs use.

## :bulb: Motivation and Context
- https://github.com/getsentry/sentry-react-native/pull/2708#discussion_r1084001203

## :green_heart: How did you test it?
With RN sample app

## :pencil: Checklist

- [x] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] No breaking changes

## :crystal_ball: Next steps
#skip-changelog

### CODE REVIEW

**Comment by krystofwoldrich** [comment]
@markushi @romtsn I optimized what I know, but I'm unsure how to expose only the `byte[]` for the RN SDK.

- https://github.com/getsentry/sentry-react-native/pull/2708#discussion_r1084159151

**Comment by krystofwoldrich** [comment]
@markushi As we discussed, I've extracted the serialization into a separate method. 
[`ac751e1` (#2492)](https://github.com/getsentry/sentry-java/pull/2492/commits/ac751e133b300f34bc57283c1de53c232cc87ed3)

**Review by markushi — APPROVED** [review]
Nice one, looks good to me!

**Review by markushi — APPROVED** [review]
LGTM!

**Pull request merged**
