### PR TITLE
Add Annotation SentryCaptureException for org.springframework.web.bind.annotation.ExceptionHandler

### PR DESCRIPTION
**Pull request by xeromank**
## :scroll: Description

Add Annotation SentryCaptureException for org.springframework.web.bind.annotation.ExceptionHandler

## :bulb: Motivation and Context

It was inconvenient to use Sentry.captureException(Exception e) in the @ExceptionHandler of @ControllerAdvice, so that part was annotated. In the process, since the company does not have a private repository, a Pull Request is made.

## :green_heart: How did you test it?
image

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by adinauer** [comment]
Thanks for the PR @xeromank. Will try to give this a review soon.

**Comment by adinauer** [comment]
I've just given this a pass, fixed some config and added tests. Before duplicating this into the non jakarta modules for Spring 5 and Spring Boot 2 I'd like to discuss some things internally:
- Should we capture `Throwable` instead?
- Do we want an option to opt-in / opt-out?
- Should we allow annotating classes as well? Probably not.
- Is handled = true what we want? Should it be a property on the annotation to allow configuring it?

**Comment by adinauer** [comment]
> Should we capture Throwable instead?
Yes

> Do we want an option to opt-in / opt-out?
Opt-out as this may be causing issues GraalVM (see #2742)

> Should we allow annotating classes as well? Probably not.
Not for now. Can always come back later and revisit.

> Is handled = true what we want? Should it be a property on the annotation to allow configuring it?
Not for now. Can always come back later and revisit.

Next step would be to copy changes over to `spring` (non `jakarta`) modules.

**Comment by xeromank** [comment]
> * Should we capture `Throwable` instead?
Yes
> * Do we want an option to opt-in / opt-out?
No. unnecessary
> * Should we allow annotating classes as well? Probably not.
No. as you expected
> * Is handled = true what we want? Should it be a property on the annotation to allow configuring it?
To be honest, I'm not sure about this part. But I think this will be convenient.

**Comment by adinauer** [comment]
@xeromank I'll take another look here but want to wait for #2788 to get merged first, resolve conflicts and only then start copying code.

**Comment by xeromank** [comment]
I checked PR(#2946).  Thanks!!
I will close this PR.

**Comment by adinauer** [comment]
Hello @xeromank the `@SentryCheckIn` annotation is for check-ins (CRONS) where the goal is to monitor a scheduled job to see if it executes on schedule and also provide a trace for it. Are you sure it replaces this PR?

**Comment by xeromank** [comment]
Hello @adinauer. thanks for explaining.
I thought it seemed to have a somewhat similar effect.
@SentryCheckIn can't play the role of Sentry.capture(), right?

**Comment by adinauer** [comment]
@xeromank well it does capture, but not errors. It captures a check-in for a CRON job. Here's some docs on the product: https://docs.sentry.io/product/crons/

I'm thinking whether we wanna reserve the name `@SentryCaptureException` for an annotation that works a bit differently from what the one in this PR does. I was thinking it could basically wrap the method in a try/catch and capture any exceptions the method throws. The annotation in this PR could be named `@SentryCaptureExceptionParam` or similar to make it more clear it captures an exception passed in to the annotated method vs. one that's thrown. What do you think?

**Comment by xeromank** [comment]
@adinauer 
I will respect your opinion. 
The name of the annotation is not important to me.
I just wish I was good at capturing exceptions.

**Comment by adinauer** [comment]
Will give this another pass and change some things later this week hopefully.

**Pull request merged**
