### PR TITLE
Update Gradle plugin dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the Gradle wrapper and Android Gradle plugin for `sentry-android-gradle-plugin`.

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by bretthoerner** [comment]
Hi @friederbluemle, did you have an issue using the plugin as it is? The reason we built with those versions is they are what React Native currently locks users to.

**Comment by Hazer** [comment]
@bretthoerner Actually, React Native projects with Android target have no issues building with those versions. I have some codes using it and are working fine, the only thing that need to be changed, is stop using that really old `23.0.1` version of the `Android Build Tools`, and update to at least `25.0.0`. I recommend using `25.0.3` as it really the last most stable or the newer `26.0.0` that is stable too, but recently released.

Android Build Tools, when stable, have almost no side-effects on updates, if you didn't change the `compileSdkVersion` it is almost like nothing changed. Their retrocompatibility are really good.

And I believe if somehow, in future updates it becomes an issue, it is not Sentry-Android fault, and the issue about Gradle should be opened on React Native repo. People who got in trouble, should use an older Sentry-Android version and open/+1 issue about newer Gradle on RN by themselves.

I believe, React Native, even being a supported platform, should not dictate bad practices/behaviour to sentry-android.

**Comment by friederbluemle** [comment]
Hi @bretthoerner, @Hazer is correct, the version updates in this PR should have no effect on projects using the Gradle plugin. They are build time only dependencies, and using the latest version will improve and speed up the build (especially Gradle has improved a lot with the latest version `4.0` compared to `2.2`).
I also agree that end user projects (e.g. React Native) should not dictate/require a library like `sentry-android` to use a specific version, i.e. prevent it from using the latest, stable version. Rather, the downstream project should be updated and fixed to work with the latest version (anyway, that's just on the side, as this PR will not affect anything in that regard). :)

**Comment by bretthoerner** [comment]
Users *could* upgrade their own dependencies to allow this to work, but the issue is that we want to work with users of the default installation (and be forward compatible for those that *do* upgrade).

I just made a new ReactNative project and it set the following:

> classpath 'com.android.tools.build:gradle:2.2.3'
> buildToolsVersion "23.0.1"

So I have to go back to my original question: did you have an issue using the plugin as it currently is?

**Comment by Hazer** [comment]
> Users could upgrade their own dependencies to allow this to work, but the issue is that we want to work with users of the default installation (and be forward compatible for those that do upgrade).

@bretthoerner Technically, I may be wrong, but the end user won't really need to update it's own project. The only update will be in [getsentry/react-native-sentry](https://github.com/getsentry/react-native-sentry) project.

I can check this tonight creating a default project, but with `getsentry/react-native-sentry` dependencies updated to see if it plays well.

**Comment by bretthoerner** [comment]
Ah OK, that's how I was taking this:

> the only thing that need to be changed, is stop using that really old 23.0.1 version of the Android Build Tools, and update to at least 25.0.0

Because we don't actually depend on the Android build tools at all in the wrapper, AFAIK?

If we upgrade everything and it still works on default React Native applications then that's great. I'm still not entirely sure what we'll get for the upgrade, though. It's like 200 lines of Groovy, I'm not concerned with compile time.

All this said, we need to automate integration testing of the wrapper somehow.

**Comment by friederbluemle** [comment]
The changes in this PR have absolutely no effect in terms of compatibility to React Native (nor should there be any kind of interdependency).

**Comment by friederbluemle** [comment]
Rebased branch onto latest `master`.

**Comment by friederbluemle** [comment]
Rebased again onto latest `master`. @bretthoerner Do you have any other questions or concerns about this?

**Comment by bretthoerner** [comment]
I just need to find the time to test it since we don't have automatic
integrations yet.

**Comment by bretthoerner** [comment]
@friederbluemle Gradle 4.0.1 bugfix is already out, do you mind swapping out your commit and then I'll merge?

**Comment by friederbluemle** [comment]
@bretthoerner Sure thing! 👍 Amended the commit and rebased my branch.

**Pull request merged**
