### PR TITLE
Android Profiler on calling thread

### PR DESCRIPTION
**Pull request by stefanosiano**
## :scroll: Description
AndroidTransactionProfiler now starts/stops profiles without offloading to the executorService
removed any file checks due to the code running possibly on the main thread
wrapped Debug methods into try/catch to compensate lack of file checks

## :bulb: Motivation and Context
If the executor service is very busy, the profiler would start with some delay, and when finishing it would wait for the executor to finish, possibly causing ANRs.
fixes https://github.com/getsentry/sentry-java/issues/2649

## :green_heart: How did you test it?
Unit test

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Review by romtsn — APPROVED** [review]
LGTM, but in the original issue this was somehow related to slow network connection. Have you managed to reproduce it? I wasn't sure how the slow connectivity can be the reason here, because our HttpConnection uses a different thread pool (also single-threaded), so in theory they should not conflict with SentryExecutorService

**Comment by stefanosiano** [comment]
> LGTM, but in the original issue this was somehow related to slow network connection. Have you managed to reproduce it? I wasn't sure how the slow connectivity can be the reason here, because our HttpConnection uses a different thread pool (also single-threaded), so in theory they should not conflict with SentryExecutorService

The `SentryExecutorService` is used by `SendCachedEnvelopeIntegration` and `SendCachedEnvelopeFireAndForgetIntegration`.
I think in case of slow connection envelopes are cached to disk and sent, but there is a wait in the [processing of the envelope file](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/EnvelopeSender.java#L70)
Does it make sense or am i missing something?
At the moment the `SentryExecutorService` is not used for any critical things anymore (except scheduling auto finish of profiling, ttfd and cpu/mem collection, but that's more to cover edge cases), but we could think about using an executor only for the envelope handling.

**Comment by romtsn** [comment]
@stefanosiano ah gotcha, that makes sense, yes! And then we were blocking on the profiler, although the executor was already busy. I think it's fine to use the executor as long as we don't call blocking `.get` on the main thread (except the startup crash case, where we block for 5s max), so this looks good

**Comment by helloword1** [comment]
When will the new version be released to fix the issue?

**Pull request merged**
