### PR TITLE
Fix not eligible for auto proxying warnings

### LINKED ISSUE #3042: Sentry Spring Boot Integration Can Produce Lots of "not eligible for getting processed by all BeanPostProcessors" Noise In Startup Logs
### Integration

sentry-spring-boot-starter-jakarta

### Java Version

21

### Version

6.33.1

### Steps to Reproduce

I created a demo repository [here](https://github.com/adase11/spring-boot-starter-sentry-demo) the details should be in the README.md.  Essentially the combination of `sentry-spring-boot-starter-jakarta` and some basic spring-boot starters (`spring-boot-starter-data-jpa` and `spring-boot-starter-web` in my case) cause lots of noise about the sentry beans not being eligible for all bean post processors in the startup logs.

I've observed this with Java 17 and Spring Boot 3.1.x as well as Java 21 and Spring Boot 3.2.x.

The noise in the logs makes it very easy to miss some change that a developer is making that is actually introducing an issue.

### Expected Result

No bean post processor noise in the logs.

### Actual Result

Lots of bean post processor noise in the logs related to sentry beans.

### PR DESCRIPTION
**Pull request by lbloder**
## :scroll: Description
Fix not eligible for auto proxying warnings by:
- Removing the hub dependency from all `Advice` Beans
- Mark all AOP related classes/methods annoted with `@Configuration` or `@Bean` with `@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
`

## :bulb: Motivation and Context
Fixes #3042 

## :green_heart: How did you test it?
Manually by checking the log output

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Review by adinauer — APPROVED** [review]
I restored the `Advice` constructors as this would be a breaking change since not all of those are marked internal.

**Comment by adinauer** [comment]
Tests still need some love.

**Comment by adase11** [comment]
Looks good on my end now. Thanks!

**Comment by adinauer** [comment]
@adase11 thanks for the feedback.

**Pull request merged**
