### PR TITLE
Vendor Json: SentryEnvelope

### PR DESCRIPTION
**Pull request by denrase**
#skip-changelog

## :scroll: Description

- Implement serialization/deserialization for `SentryEnvelopeHeader`
- Implement serialization/deserialization for `SentryEnvelopeItemHeader`

## :green_heart: How did you test it?

- Added tests.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
@bruno-garcia wondering if we need to implement the `JsonUnknown` strategy here too (since it's the envelope bits), wdyt?

**Comment by denrase** [comment]
Figured it's very unlikely that the envelope and envelope item headers will change, but that's probably true for many other models as well. We can add them as well.

**Comment by marandaneto** [comment]
> Figured it's very unlikely that the envelope and envelope item headers will change, but that's probably true for many other models as well. We can add them as well.

yeah lets add it then

**Comment by denrase** [comment]
@marandaneto done

**Pull request merged**
