### PR TITLE
feat: Update sentry-native to 0.4.4

### PR DESCRIPTION
**Pull request by Swatinem**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring

## :scroll: Description

Updating to the latest sentry-native release, and making sure it is built as dynamic library.

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by marandaneto** [comment]
it didn't work, I can see this on travis ci:

[55/56] Linking CXX static library sentry_build/libsentry.a
[56/56] Linking CXX shared library ../../../../build/intermediates/cmake/release/obj/x86_64/libnative-sample.so

**Review by marandaneto — CHANGES_REQUESTED** [review]
`set(SENTRY_BUILD_SHARED_LIBS ON)` only doesnt work

**Comment by marandaneto** [comment]
also appveyor:
[54/55] Linking CXX static library sentry_build\libsentry.a
[55/55] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\release\obj\arm64-v8a\libnative-sample.so
Build native-sample_x86

**Comment by Swatinem** [comment]
I get this on travis now:

```
[54/55] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libsentry.so
```

**Comment by marandaneto** [comment]
can confirm. thanks

**Review by marandaneto — APPROVED** [review]
LGTM

**Pull request merged**
