### PR TITLE
release: 6.7.0

### PR DESCRIPTION
**Pull request by vaind**
This is a tagged release but not merged to the main branch - can anyone merge it **without squashing** (otherwise the release commit would say it doesn't exist in the repo?

#skip-changelog

### CODE REVIEW

**Comment by romtsn** [comment]
Sorry I didn't get, why do we need this? Isn't this already existing https://github.com/getsentry/sentry-java/commit/78ede0b026381677987886510df1265e480ebd93 ?

**Comment by vaind** [comment]
> Sorry I didn't get, why do we need this? Isn't this already existing [78ede0b](https://github.com/getsentry/sentry-java/commit/78ede0b026381677987886510df1265e480ebd93) ?

that commit is not on the main branch, unlike normal releases that haven't failed at some point in the release process

**Review by romtsn — APPROVED** [review]

**Comment by romtsn** [comment]
@vaind gotcha, I enabled regular merge with a new commit creation - is that what you need? I think you can also use it

**Comment by vaind** [comment]
> @vaind gotcha, I enabled regular merge with a new commit creation - is that what you need? I think you can also use it

thanks, can you approve it too? I can't merge otherwise

**Comment by romtsn** [comment]
I already approved, I guess it wants you to update the branch with latest `main` first?

**Pull request merged**
