### PR TITLE
Add an option for opting out of pretty print

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

A new option to disable pretty printing of events in the debug log.

## :bulb: Motivation and Context

In backend applications there's often many errors and transactions as well as other logs making it hard to look at / copy an event. With pretty print disabled an event takes up only a single line and can more easily be copy pasted to another tool for formatting where output doesn't get rotated out etc.

## :pencil: Checklist

- [ ] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by adinauer** [comment]
@romtsn @markushi @stefanosiano what do you think about the naming? I'd like to decide on a name before going ahead and implementing other forms of configuration for this new property.

**Comment by markushi** [comment]
> @romtsn @markushi @stefanosiano what do you think about the naming? I'd like to decide on a name before going ahead and implementing other forms of configuration for this new property.

`prettyPrintSerializationOutput` sounds good to me, IMHO `enablePrettySerializationOutput` could work well too.

**Comment by adinauer** [comment]
Renamed it to `enablePrettySerializationOutput` and added it to `ExternalOptions`. Didn't add it to Android Manifest options, as I've never heard any Android user request this. Let me know if I should add it.

**Review by markushi — APPROVED** [review]
LGTM!

**Pull request merged**
