### PR TITLE
Align how to add an ignored Exception with other SDKs

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

Add another way to add ignored Exceptions called `addExceptionFilterForType` in addition to the already existing `addIgnoredExceptionForType `. 

## :bulb: Motivation and Context

Fixes https://github.com/getsentry/sentry-java/issues/1532

## :green_heart: How did you test it?
Unit Tests

## :pencil: Checklist

- [ ] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] No breaking changes

## :crystal_ball: Next steps
* Discuss whether we want to deprecate `addIgnoredExceptionForType`

### CODE REVIEW

**Comment by romtsn** [comment]
> Regarding docs: should this be a common option that SDKs can opt into? Currently .NET only documents this here [docs.sentry.io/platforms/dotnet/usage/#ignoring-errors](https://docs.sentry.io/platforms/dotnet/usage/#ignoring-errors) but not in [docs.sentry.io/platforms/dotnet/configuration/options](https://docs.sentry.io/platforms/dotnet/configuration/options/)

Dunno the policy here, but imho it should be added there, since it's part of the SentryOptions class

**Comment by romtsn** [comment]
> Discuss whether we want to deprecate addIgnoredExceptionForType

Or can we actually remove it altogether, since it's going into a new major anyway?

**Review by romtsn — APPROVED** [review]

**Comment by adinauer** [comment]
> > Discuss whether we want to deprecate addIgnoredExceptionForType
> 
> Or can we actually remove it altogether, since it's going into a new major anyway?

We decided not to do so here https://github.com/getsentry/sentry-java/issues/1532

**Comment by romtsn** [comment]
> > > Discuss whether we want to deprecate addIgnoredExceptionForType
> > 
> > 
> > Or can we actually remove it altogether, since it's going into a new major anyway?
> 
> We decided not to do so here #1532

ah ok, deprecate it then?

**Comment by adinauer** [comment]
> > > > Discuss whether we want to deprecate addIgnoredExceptionForType
> > > 
> > > 
> > > Or can we actually remove it altogether, since it's going into a new major anyway?
> > 
> > 
> > We decided not to do so here #1532
> 
> ah ok, deprecate it then?

Hmm as explained here https://github.com/getsentry/sentry-java/issues/1532#issuecomment-1113007564 ff I'd prefer keeping both. Or at least keep the old naming internally as it makes more sense. But if you'd prefer it to be deprecated, I can deprecate it.

**Comment by romtsn** [comment]
I guess it's fine to keep the old internal naming, I was just talking about the method in the public api

**Comment by adinauer** [comment]
Created docs PR here: https://github.com/getsentry/sentry-docs/pull/4995

Found another difference between Java and .NET. Classes derived from the exception type added will also be ignored in .NET but not in Java. In Java you have to explicitly add every type to the list. Should I create an issue to further discuss this?

**Comment by adinauer** [comment]
Opened https://github.com/getsentry/sentry-java/issues/2015 in case we want to align subclasses being ignored with .NET.

**Pull request closed without merging**
