### PR TITLE
Only send userid in `baggage` if `sendDefaultPii` is `true`

### PR DESCRIPTION
**Pull request by adinauer**
## :bulb: Motivation and Context

`userid` is considered PII and now hidden behind `sendDefaultPii`.

## :green_heart: How did you test it?
Unit tests

## :pencil: Checklist

- [ ] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] No breaking changes

### CODE REVIEW

**Comment by adinauer** [comment]
fyi @brustolin

**Comment by bruno-garcia** [comment]
@adinauer Is this really the way to go? this flag guards other PII data so I feel this will stop ppl from using it

**Comment by bruno-garcia** [comment]
Sorry closed accidently because CMD + Enter is fucked

**Comment by adinauer** [comment]
Closing in favor of https://github.com/getsentry/sentry-java/pull/2147 to also skip `userId` in envelope header `trace`.

**Pull request closed without merging**
