### PR TITLE
fix: Make sure that scope is popped after all events are recorded.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Servlet filters finish execution too soon causing unhandled exceptions being logged after scope is already popped - which could have been easily seen when Spring and Logback integrations were active at once.

This change makes Spring integration use `ServletRequestListener` which is called at the very beginning and very end of the request processing.

## :green_heart: How did you test it?

Manually by debugging with breakpoints. To test it in automated fashion we would have to have a separate module for cross-module integration tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

`SentrySpringRequestListener` is very similar to `SentryServletRequestListener` and I think there is a space here for reducing duplication and making Spring integration use servlet module. Not something to do now a day before the release but we can think about it in the future.

### CODE REVIEW

**Review by marandaneto — APPROVED** [review]

**Comment by maciejwalkowiak** [comment]
@marandaneto is Codecov properly configured? I am not sure what is it complaining about.

**Comment by marandaneto** [comment]
> @marandaneto is Codecov properly configured? I am not sure what is it complaining about.

nothing has changed, not sure either, I am not on the codecov org though, cant check the config.
@bruno-garcia ?

**Review by bruno-garcia — APPROVED** [review]
👍

**Comment by bruno-garcia** [comment]
Looks like it's nagging because of -0.01% I've tried to configure that in the past and gave up

**Pull request merged**
