### PR TITLE
Change OkHttp sub-spans to span attributes

### PR DESCRIPTION
**Pull request by stefanosiano**
## :scroll: Description
SentryOkHttpEvent now set data instead of creating child spans
renamed constants to make them nicer in the UI
SentryOkHttpInterceptor now closes the listener call

[Before](https://sentry-sdks.sentry.io/performance/trace/9e4523f514dd49cf8e6902a3de94af25/?node=span-080479a614234019&node=txn-4f56a4eb30da4150ac7d0818e99a10fb&project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=14d&timestamp=1719498761&transaction=SecondActivity&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

Screenshot 2024-07-08 at 12 06 37

[After](https://sentry-sdks.sentry.io/performance/trace/d8e2db038c254758b419da8a57c3ecb7/?node=span-6eb58507b1fa4033&node=txn-6ec8c14919854bcb822eb364d7201a76&project=5428559&query=&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=1h&timestamp=1720446593&transaction=SecondActivity&transactionCursor=0%3A0%3A1&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

Screenshot 2024-07-08 at 15 52 02

## :bulb: Motivation and Context
Closes https://github.com/getsentry/sentry-java/issues/3520

## :pencil: Checklist

- [ ] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by gggritso** [comment]
This is awesome thank you! Really great for how Insights shows this data, too! Would be great to also align to how the JavaScript SDK records the connection timings:

```
"http.request.connect_start": 1720444446.0359,
"http.request.connection_end": 1720444446.0359,
"http.request.domain_lookup_end": 1720444446.0359,
"http.request.domain_lookup_start": 1720444446.0359,
"http.request.fetch_start": 1720444446.0359,
"http.request.redirect_start": 1720444445.188,
"http.request.request_start": 1720444446.0493,
"http.request.response_start": 1720444446.0962,
"http.request.response_end": 1720444446.0963,
"http.request.secure_connection_start": 1720444446.0359,
```

That way, these measurements will show up with a nicer UI in the trace view. Unsure if this is standardized somewhere, but would love to all SDKs to report these measurements the same way.

**Comment by kahest** [comment]
> This is awesome thank you! Really great for how Insights shows this data, too! Would be great to also align to how the JavaScript SDK records the connection timings:
[...]
> That way, these measurements will show up with a nicer UI in the trace view. Unsure if this is standardized somewhere, but would love to all SDKs to report these measurements the same way.

Thanks for bringing this up, definitely good to align! We landed on the key names you see in this PR because that we we kinda reproduce the nested spans we had before (e.g. `http.connection` contains child spans `http.connection.request_header`, `http.connection.response_body`, etc.). Do you think this makes sense or should we aim to align with JS fully?

**Comment by gggritso** [comment]
@kahest 🤔 I think this decision is best left to the SDK folks! The important thing to the UI is that the measurements have the same names in every SDK that supports them. If you align to JS that makes the UI work easy (since it's already done). If you decide to _not_ align to JS, you'll need to let us know what the names will be, and we can adjust the UI code, and then update the JS SDK output to match?

For what it's worth, right now the UI specifically treats these two measurements as special: `"http.request.request_start"` and `"http.request.response_start"`. If they are present, it shows nice little duration lines in the span data section in the trace view:
Screenshot 2024-07-09 at 1 46 44 PM

We don't do anything special with the other measurements, but we might in the future! e.g., there was some talk of adding more metrics to the Requests Insights module to track connection times.

**Comment by stefanosiano** [comment]
@gggritso from what i understand `http.request.request_start` and `http.request.response_start` are not durations, but timestamps, right?

**Comment by gggritso** [comment]
@stefanosiano that's correct!

**Pull request merged**
