### PR TITLE
Handle AppEngine quirks in SentryHandler.

### PR DESCRIPTION
**Pull request by bretthoerner**
The fixes here come from the great summary found here (required reading): https://github.com/getsentry/raven-java/issues/228

Still have to figure out how to best setup a `SentryHandler` on AppEngine (with the correct `RavenFactory` no less). It appears some people do `Logger.getLogger("").addHandler(new SentryHandler());` -- but then where does the config come from? AppEngine seems to disallow setting up other loggers in the properties file.

### CODE REVIEW

**Comment by wholegroup** [comment]
@bretthoerner sorry for such delay

There is also an another issue how to change log level (by default it's `Level.ALL`), because the code of `java.util.logging.Handler.setLevel` has `checkPermission()` call and GAE throws `SecurityException`. 

p.s.
It would be great to have a short description in readme how to enable SentryHandler in GAE,
as you wrote `Logger.getLogger("").addHandler(new SentryHandler());`

**Comment by bretthoerner** [comment]
So how do you change the log level on App Engine?

**Comment by wholegroup** [comment]
@bretthoerner I don't do that. I added a new private field `logLevel` in my handler, copied code from `java.util.logging.Handler.isLoggable` instead of calling `super.isLoggable(record)`, and overridden 'setLevel'. Also I added loading `com.getsentry.raven.jul.SentryHandler.level` property

That doesn't look like a proper way that's why I suggested to make a dedicated handler to use in GAE

**Comment by bretthoerner** [comment]
Need to revisit thing entire branch.

**Pull request closed without merging**
